version: "3.7"
services:
  app:
    build:
      args:
        user: bdf
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: aiverberie
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - landing

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - landing

  db:
    image: mysql:5.7
    command: --max_allowed_packet=325058560000
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - landing

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    networks:
      - landing

networks:
  landing:
    driver: bridge
